In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("juhibhojani/house-price")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/juhibhojani/house-price/1.archive...

100%|██████████| 6.61M/6.61M [00:00<00:00, 106MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/juhibhojani/house-price/versions/1

In [ ]:
df= pd.read_csv(f"{path}/house_prices.csv")

In [ ]:
df.head()

,Index,Title,Description,Amount(in rupees),Price (in rupees),location,Carpet Area,Status,Floor,Transaction,...,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area
0,0,1 BHK Ready to Occupy Flat for sale in Srushti...,"Bhiwandi, Thane has an attractive 1 BHK Flat f...",42 Lac,6000.0,thane,500 sqft,Ready to Move,10 out of 11,Resale,...,NaN,NaN,Srushti Siddhi Mangal Murti Complex,1,2,NaN,NaN,NaN,NaN,NaN
1,1,2 BHK Ready to Occupy Flat for sale in Dosti V...,One can find this stunning 2 BHK flat for sale...,98 Lac,13799.0,thane,473 sqft,Ready to Move,3 out of 22,Resale,...,East,Garden/Park,Dosti Vihar,2,NaN,1 Open,Freehold,NaN,NaN,NaN
2,2,2 BHK Ready to Occupy Flat for sale in Sunrise...,Up for immediate sale is a 2 BHK apartment in ...,1.40 Cr,17500.0,thane,779 sqft,Ready to Move,10 out of 29,Resale,...,East,Garden/Park,Sunrise by Kalpataru,2,NaN,1 Covered,Freehold,NaN,NaN,NaN
3,3,1 BHK Ready to Occupy Flat for sale Kasheli,This beautiful 1 BHK Flat is available for sal...,25 Lac,NaN,thane,530 sqft,Ready to Move,1 out of 3,Resale,...,NaN,NaN,NaN,1,1,NaN,NaN,NaN,NaN,NaN
4,4,2 BHK Ready to Occupy Flat for sale in TenX Ha...,"This lovely 2 BHK Flat in Pokhran Road, Thane ...",1.60 Cr,18824.0,thane,635 sqft,Ready to Move,20 out of 42,Resale,...,West,"Garden/Park, Main Road",TenX Habitat Raymond Realty,2,NaN,1 Covered,Co-operative Society,NaN,NaN,NaN

In [ ]:
df.describe()

               Index  Price (in rupees)  Dimensions  Plot Area
count  187531.000000       1.698660e+05         0.0        0.0
mean    93765.000000       7.583772e+03         NaN        NaN
std     54135.681003       2.724171e+04         NaN        NaN
min         0.000000       0.000000e+00         NaN        NaN
25%     46882.500000       4.297000e+03         NaN        NaN
50%     93765.000000       6.034000e+03         NaN        NaN
75%    140647.500000       9.450000e+03         NaN        NaN
max    187530.000000       6.700000e+06         NaN        NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 21 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Description        184508 non-null  object
 3   Amount(in rupees)  187531 non-null  object
 4   Price (in rupees)  169866 non-null  float64
 5   location           187531 non-null  object
 6   Carpet Area        106858 non-null  object
 7   Status             186916 non-null  object
 8   Floor              180454 non-null  object
 9   Transaction        187448 non-null  object
 10  Furnishing         184634 non-null  object
 11  facing             117298 non-null  object
 12  overlooking        106095 non-null  object
 13  Society            77853 non-null   object
 14  Bathroom           186703 non-null  object
 15  Balcony            138596 non-null  object
 16  Car Parking        84174 non-null   object
 17  Ownership          122014 non-null  object
 18  Super Area         79846 non-null   object
 19  Dimensions         0 non-null       float64
 20  Plot Area          0 non-null       float64
dtypes: float64(3), int64(1), object(17)
memory usage: 30.0+ MB

In [ ]:
df.columns

Index(['Index', 'Title', 'Description', 'Amount(in rupees)',
       'Price (in rupees)', 'location', 'Carpet Area', 'Status', 'Floor',
       'Transaction', 'Furnishing', 'facing', 'overlooking', 'Society',
       'Bathroom', 'Balcony', 'Car Parking', 'Ownership', 'Super Area',
       'Dimensions', 'Plot Area'],
      dtype='object')

In [ ]:
df.isna().sum()

Index                     0
Title                     0
Description            3023
Amount(in rupees)         0
Price (in rupees)     17665
location                  0
Carpet Area           80673
Status                  615
Floor                  7077
Transaction              83
Furnishing             2897
facing                70233
overlooking           81436
Society              109678
Bathroom                828
Balcony               48935
Car Parking          103357
Ownership             65517
Super Area           107685
Dimensions           187531
Plot Area            187531
dtype: int64

In [ ]:
df.drop(columns=["Dimensions","Plot Area"], inplace=True)

In [ ]:
df.drop(columns=["Description"], inplace=True)

In [ ]:
def convert_price(x):
    if pd.isna(x):
        return np.nan
    x = str(x).replace(',', '').strip()

    if "Lac" in x:
        return float(x.replace("Lac", "")) * 1e5
    elif "Cr" in x:
        return float(x.replace("Cr", "")) * 1e7
    else:
        try:
            return float(x)
        except ValueError:
            return np.nan # Handle 'Call for Price' and other non-numeric strings

df["Amount(in rupees)"] = df["Amount(in rupees)"].apply(convert_price)

In [ ]:
def extract_sqft(x):
    if pd.isna(x):
        return np.nan
    x = str(x).lower()
    num = ''.join([c for c in x if c.isdigit() or c == '.'])
    return float(num) if num != '' else np.nan

for col in ["Carpet Area", "Super Area"]:
    df[col] = df[col].apply(extract_sqft)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187531 entries, 0 to 187530
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              187531 non-null  int64
 1   Title              187531 non-null  object
 2   Amount(in rupees)  177847 non-null  float64
 3   Price (in rupees)  169866 non-null  float64
 4   location           187531 non-null  object
 5   Carpet Area        106858 non-null  float64
 6   Status             186916 non-null  object
 7   Floor              180454 non-null  object
 8   Transaction        187448 non-null  object
 9   Furnishing         184634 non-null  object
 10  facing             117298 non-null  object
 11  overlooking        106095 non-null  object
 12  Society            77853 non-null   object
 13  Bathroom           186703 non-null  object
 14  Balcony            138596 non-null  object
 15  Car Parking        84174 non-null   object
 16  Ownership          122014 non-null  object
 17  Super Area         79846 non-null   float64
dtypes: float64(4), int64(1), object(13)
memory usage: 25.8+ MB

In [ ]:
def extract_floor(x):
    try:
        return int(str(x).split(" ")[0])
    except:
        return np.nan

def extract_total_floor(x):
    try:
        return int(str(x).split("out of")[1])
    except:
        return np.nan

df["Floor_num"] = df["Floor"].apply(extract_floor)
df["Total_Floor"] = df["Floor"].apply(extract_total_floor)

df.drop(columns=["Floor"], inplace=True)

In [ ]:
cols = ["Bathroom", "Balcony", "Car Parking"]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [ ]:
def extract_bhk(x):
    import re
    match = re.search(r'(\d+)\s*BHK', str(x))
    return int(match.group(1)) if match else np.nan

df["BHK"] = df["Title"].apply(extract_bhk)

In [ ]:
#df.drop(columns=["Title", "Description"], inplace=True)
df.drop(columns=["Car Parking"], inplace = True)

In [ ]:
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [ ]:
df.dropna(inplace=True)

In [ ]:
cat_cols = ["Status", "Transaction", "Furnishing", "facing", "overlooking", "Ownership"]
#cat_cols_ = ["location"]
df = pd.get_dummies(df, columns=cat_cols)

In [ ]:
df.drop(columns=["Title"], inplace=True)
df.head()

,Index,Amount(in rupees),Price (in rupees),location,Carpet Area,Society,Bathroom,Balcony,Super Area,Floor_num,...,overlooking_Pool,"overlooking_Pool, Garden/Park","overlooking_Pool, Garden/Park, Main Road","overlooking_Pool, Main Road","overlooking_Pool, Main Road, Garden/Park","overlooking_Pool, Main Road, Not Available",Ownership_Co-operative Society,Ownership_Freehold,Ownership_Leasehold,Ownership_Power Of Attorney
1,1,9800000.0,13799.0,thane,473.0,Dosti Vihar,2.0,2.0,1250.0,3.0,...,False,False,False,False,False,False,False,True,False,False
2,2,14000000.0,17500.0,thane,779.0,Sunrise by Kalpataru,2.0,2.0,1250.0,10.0,...,False,False,False,False,False,False,False,True,False,False
4,4,16000000.0,18824.0,thane,635.0,TenX Habitat Raymond Realty,2.0,2.0,1250.0,20.0,...,False,False,False,False,False,False,True,False,False,False
5,5,4500000.0,6618.0,thane,1000.0,Virat Aangan,1.0,1.0,680.0,2.0,...,False,False,False,False,False,False,True,False,False,False
9,9,16000000.0,11150.0,thane,900.0,Pride Palms,3.0,1.0,1250.0,3.0,...,False,False,False,False,False,False,False,True,False,False

In [ ]:
df["Society"].value_counts()

Society
Hamdam Apartment           1648
Malibu Town                1156
Shree Vardhman Victoria    1154
DLF Skycourt               1150
Harmony Apartment           828
                           ...
Sushma Capital                1
Motia Homes                   1
VIP Road Zirakpur             1
Gold Mark                     1
GMS Apartments                1
Name: count, Length: 6624, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["Price (in rupees)", "Amount(in rupees)"])
y = df[["Price (in rupees)","Amount(in rupees)"]]
#y = y = df["Price (in rupees)"]
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
society_mean = pd.concat([X_train["Society"], y_train], axis=1) \
                 .groupby("Society")["Price (in rupees)"].mean()

In [ ]:
# Apply on train
X_train["society_encoded"] = X_train["Society"].map(society_mean)

# Apply on test (IMPORTANT: same mapping)
X_test["society_encoded"] = X_test["Society"].map(society_mean)

In [ ]:
global_mean = y_train.mean()

X_train["society_encoded"].fillna(global_mean, inplace=True)
X_test["society_encoded"].fillna(global_mean, inplace=True)

/tmp/ipykernel_3419/3911983352.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["society_encoded"].fillna(global_mean, inplace=True)
/tmp/ipykernel_3419/3911983352.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["society_encoded"].fillna(global_mean, inplace=True)

In [ ]:
X_train.drop(columns=["Society"], inplace=True)
X_test.drop(columns=["Society"], inplace=True)

In [ ]:
X_train

,Index,location,Carpet Area,Bathroom,Balcony,Super Area,Floor_num,Total_Floor,BHK,Status_Ready to Move,...,"overlooking_Pool, Garden/Park","overlooking_Pool, Garden/Park, Main Road","overlooking_Pool, Main Road","overlooking_Pool, Main Road, Garden/Park","overlooking_Pool, Main Road, Not Available",Ownership_Co-operative Society,Ownership_Freehold,Ownership_Leasehold,Ownership_Power Of Attorney,society_encoded
69244,69244,gurgaon,1000.0,4.0,3.0,1932.0,14.0,15.0,4.0,True,...,False,False,False,False,False,False,True,False,False,6522.000000
125123,125123,new-delhi,1000.0,2.0,2.0,1250.0,1.0,2.0,2.0,True,...,False,False,False,False,False,False,True,False,False,13329.073463
125933,125933,new-delhi,1000.0,2.0,2.0,1250.0,1.0,2.0,2.0,True,...,False,False,False,False,False,False,True,False,False,13329.073463
105063,105063,kolkata,1450.0,3.0,2.0,1250.0,18.0,28.0,3.0,True,...,False,False,False,False,False,False,True,False,False,6196.742063
53985,53985,gurgaon,1800.0,4.0,2.0,1250.0,6.0,14.0,4.0,True,...,False,False,False,False,False,False,True,False,False,8333.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60430,60430,gurgaon,1700.0,4.0,4.0,1250.0,2.0,2.0,4.0,True,...,False,False,False,False,False,False,True,False,False,14250.000000
161799,161799,greater-noida,960.0,4.0,5.0,1250.0,5.0,17.0,3.0,True,...,False,False,False,False,False,False,False,True,False,3380.000000
142748,142748,new-delhi,1300.0,2.0,2.0,1250.0,5.0,7.0,3.0,True,...,False,False,False,False,False,False,True,False,False,9875.000000
2311,2311,mumbai,864.0,2.0,2.0,1250.0,18.0,35.0,2.0,True,...,True,False,False,False,False,False,True,False,False,20168.666667
67194,67194,gurgaon,1000.0,3.0,1.0,1920.0,2.0,20.0,3.0,True,...,False,False,False,False,False,False,True,False,False,8054.520087

In [ ]:
mean_price = df.groupby("location")["Amount(in rupees)"].mean()

df["location_encoded"] = df["location"].map(mean_price)

In [ ]:
location_mean = pd.concat([X_train["location"], y_train], axis=1) \
                 .groupby("location")["Price (in rupees)"].mean()

X_train["location_encoded"] = X_train["location"].map(location_mean)
X_test["location_encoded"] = X_test["location"].map(location_mean)

In [ ]:
X_train["location_encoded"].fillna(global_mean["Price (in rupees)"], inplace=True)
X_test["location_encoded"].fillna(global_mean["Price (in rupees)"], inplace=True)
X_test["society_encoded"].fillna(global_mean["Price (in rupees)"], inplace=True)

/tmp/ipykernel_3419/2344847777.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train["location_encoded"].fillna(global_mean["Price (in rupees)"], inplace=True)
/tmp/ipykernel_3419/2344847777.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["location_encoded"].fillna(global_mean["Price (in rupees)"], inplace=True)
/tmp/ipykernel_3419/2344847777.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test["society_encoded"].fillna(global_mean["Price (in rupees)"], inplace=True)

In [ ]:
X_train.drop(columns=["location"], inplace=True)
X_test.drop(columns=["location"], inplace=True)

In [ ]:
display(X_train.head())

,Index,Carpet Area,Bathroom,Balcony,Super Area,Floor_num,Total_Floor,BHK,Status_Ready to Move,Transaction_New Property,...,"overlooking_Pool, Garden/Park, Main Road","overlooking_Pool, Main Road","overlooking_Pool, Main Road, Garden/Park","overlooking_Pool, Main Road, Not Available",Ownership_Co-operative Society,Ownership_Freehold,Ownership_Leasehold,Ownership_Power Of Attorney,society_encoded,location_encoded
69244,69244,1000.0,4.0,3.0,1932.0,14.0,15.0,4.0,True,False,...,False,False,False,False,False,True,False,False,6522.000000,10870.940731
125123,125123,1000.0,2.0,2.0,1250.0,1.0,2.0,2.0,True,False,...,False,False,False,False,False,True,False,False,13329.073463,10939.026628
125933,125933,1000.0,2.0,2.0,1250.0,1.0,2.0,2.0,True,False,...,False,False,False,False,False,True,False,False,13329.073463,10939.026628
105063,105063,1450.0,3.0,2.0,1250.0,18.0,28.0,3.0,True,False,...,False,False,False,False,False,True,False,False,6196.742063,7715.799737
53985,53985,1800.0,4.0,2.0,1250.0,6.0,14.0,4.0,True,False,...,False,False,False,False,False,True,False,False,8333.000000,10870.940731

In [ ]:
X_train = X_train.astype(float)

In [ ]:
X_test = X_test.astype(float)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.fit_transform(X_test)

In [ ]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train, y_train)

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn = KNeighborsRegressor(n_neighbors=5)
model_knn = knn.fit(X_train, y_train)

In [ ]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
model_dt = dt.fit(X_train, y_train)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
model_rf = rf.fit(X_train, y_train)

In [ ]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error

In [ ]:
#R2 score of decison tree model
y_train_pred = model_dt.predict(X_train)
y_pred = model_dt.predict(X_test)

print("Train R2:", r2_score(y_train, y_train_pred))
print("Test R2:", r2_score(y_test, y_pred))

Train R2: 1.0
Test R2: 0.881271144001361

In [ ]:
#R2 score of random forest model
y_train_pred = model_rf.predict(X_train)
y_pred = model_rf.predict(X_test)

print("Train R2 of y_train:", r2_score(y_train, y_train_pred))
print("Test R2 of y_test:", r2_score(y_test, y_pred))
print("Meam Squared error of y_train:",  mean_squared_error(y_train, y_train_pred))
print("Meam Squared error of y_test:",  mean_squared_error(y_test, y_pred))

Train R2 of y_train: 0.9015324984993436
Test R2 of y_test: 0.8843939181510928
Meam Squared error of y_train: 12520462521920.443
Meam Squared error of y_test: 14252923380277.695

In [ ]:
import pickle
pickle.dump(model, open("model_rf.pkl", "wb"))

In [ ]:
#R2 score of Linear regression model
y_train_pred = model.predict(X_train)
y_pred = model.predict(X_test)

print("Train R2:", r2_score(y_train, y_train_pred))
print("Test R2:", r2_score(y_test, y_pred))

Train R2: 0.8680604040564821
Test R2: 0.7417194195930671

In [ ]:
#R2 score of knn model
y_train_pred = model_knn.predict(X_train)
y_pred = model_knn.predict(X_test)

print("Train R2:", r2_score(y_train, y_train_pred))
print("Test R2:", r2_score(y_test, y_pred))

Train R2: 0.6077371652334858
Test R2: 0.8548154426617369

In [ ]:
X_train

,Index,Carpet Area,Bathroom,Balcony,Super Area,Floor_num,Total_Floor,BHK,Status_Ready to Move,Transaction_New Property,...,"overlooking_Pool, Garden/Park, Main Road","overlooking_Pool, Main Road","overlooking_Pool, Main Road, Garden/Park","overlooking_Pool, Main Road, Not Available",Ownership_Co-operative Society,Ownership_Freehold,Ownership_Leasehold,Ownership_Power Of Attorney,society_encoded,location_encoded
69244,69244.0,1000.0,4.0,3.0,1932.0,14.0,15.0,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6522.000000,10870.940731
125123,125123.0,1000.0,2.0,2.0,1250.0,1.0,2.0,2.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,13329.073463,10939.026628
125933,125933.0,1000.0,2.0,2.0,1250.0,1.0,2.0,2.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,13329.073463,10939.026628
105063,105063.0,1450.0,3.0,2.0,1250.0,18.0,28.0,3.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6196.742063,7715.799737
53985,53985.0,1800.0,4.0,2.0,1250.0,6.0,14.0,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,8333.000000,10870.940731
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60430,60430.0,1700.0,4.0,4.0,1250.0,2.0,2.0,4.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,14250.000000,10870.940731
161799,161799.0,960.0,4.0,5.0,1250.0,5.0,17.0,3.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3380.000000,5442.984235
142748,142748.0,1300.0,2.0,2.0,1250.0,5.0,7.0,3.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,9875.000000,10939.026628
2311,2311.0,864.0,2.0,2.0,1250.0,18.0,35.0,2.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,20168.666667,22033.607387
67194,67194.0,1000.0,3.0,1.0,1920.0,2.0,20.0,3.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,8054.520087,10870.940731